# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testframework' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testframework
   pod 'oriframework', :path => "../oriframework/" 


  target 'testframeworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'testframeworkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
